name: pr-build-deploy

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

jobs:
  build-deploy:
#    runs-on: yahoo-enterprise-ubuntu-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ github.token }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60