name: pr-build-deploy

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

jobs:
  build-deploy:
#    runs-on: yahoo-enterprise-ubuntu-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build rpm and test
        shell: bash
        run: |
          if [ -f "build.gradle" ]; then
             ./gradlew clean build
          fi

      - name: Upload Junit Test Result
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: './build/test-results/test/*.xml'

      - name: Publish Test Report as PR Comment
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: './build/test-results/test/*.xml'
          reporter: java-junit
          token: ${{ github.token }}