name: pr-build-deploy

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  deployments: write
  id-token: write
  pull-requests: write

jobs:
  build-deploy:
#    runs-on: yahoo-enterprise-ubuntu-x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build rpm and test
        shell: bash
        run: |
          if [ -f "build.gradle" ]; then
             ./gradlew clean build
          fi

      - name: Store HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: "${{github.workspace}}/build/reports/jacoco/test/html/"

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ github.token }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          continue-on-error: false
          debug-mode: true
#          skip-if-no-changes: true

      - name: Fail PR if overall coverage is less than threshold
        if: ${{ steps.jacoco.outputs.coverage-overall < 50.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 50%!')

      - name: Fail PR if changed files coverage is less than threshold
        if: ${{ steps.jacoco.outputs.coverage-changed-files < 50.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Changed files coverage is less than 50%!')
